# import = ["~/.config/alacritty/catppuccin-theme.toml"]

[env]
TERM = "xterm-256color"

[window]
# dimensions = { columns = 120, lines = 60 }
# position = { x = 100, y = 0 }
padding = { x = 6, y = 6}
dynamic_padding = true
decorations = "Full" # Full or None
opacity = 0.9
blur = true
startup_mode = "Windowed" # Windowed, Maximized, Fullscreen
#option_as_alt = "Both"

[font]
# normal.family = "Cascadia Code"
normal.family = "FiraCode Nerd Font Mono"
# normal.family = "JetBrainsMono Nerd Font"
size = 13

[selection]
save_to_clipboard = true


