[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 60 }
position = { x = 100, y = 0 }
padding = { x = 6, y = 6}

#decorations = "Buttonless"

opacity = 0.7
blur = true

#option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font Mono"

size = 13
